import { SelectData } from '@/types/User';

export const selectData: SelectData = {
  gender: [
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
    { label: 'Prefer not to say', value: 'Prefer not to say' },
  ],
  age: [
    { label: 'Teens', value: 'Teens' },
    { label: 'Twenties', value: 'Twenties' },
    { label: 'Thirties', value: 'Thirties' },
    { label: 'Fourties', value: 'Fourties' },
    { label: 'Fifties +', value: 'Fifties +' },
    { label: 'Prefer not to say', value: 'Prefer not to say' },
  ],
  servers: {
    dataCenter: [
      { label: 'ManaDC', value: 'ManaDC' },
      { label: 'ElementalDC', value: 'ElementalDC' },
      { label: 'GaiaDC', value: 'GaiaDC' },
      { label: 'MeteorDC', value: 'MeteorDC' },
    ],
    server: {
      ElementalDC: [
        { label: 'Aegis', value: 'Aegis' },
        { label: 'Atomos', value: 'Atomos' },
        { label: 'Carbuncle', value: 'Carbuncle' },
        { label: 'Garuda', value: 'Garuda' },
        { label: 'Gungnir', value: 'Gungnir' },
        { label: 'Kujata', value: 'Kujata' },
        { label: 'Tonberry', value: 'Tonberry' },
        { label: 'Typhon', value: 'Typhon' },
      ],
      GaiaDC: [
        { label: 'Alexander', value: 'Alexander' },
        { label: 'Bahamut', value: 'Bahamut' },
        { label: 'Durandal', value: 'Durandal' },
        { label: 'Fenrir', value: 'Fenrir' },
        { label: 'Ifrit', value: 'Ifrit' },
        { label: 'Ridill', value: 'Ridill' },
        { label: 'Tiamat', value: 'Tiamat' },
        { label: 'Ultima', value: 'Ultima' },
      ],
      ManaDC: [
        { label: 'Anima', value: 'Anima' },
        { label: 'Asura', value: 'Asura' },
        { label: 'Chocobo', value: 'Chocobo' },
        { label: 'Hades', value: 'Hades' },
        { label: 'Ixion', value: 'Ixion' },
        { label: 'Masamune', value: 'Masamune' },
        { label: 'Pandaemonium', value: 'Pandaemonium' },
        { label: 'Titan', value: 'Titan' },
      ],
      MeteorDC: [
        { label: 'Belias', value: 'Belias' },
        { label: 'Mandragora', value: 'Mandragora' },
        { label: 'Ramuh', value: 'Ramuh' },
        { label: 'Shinryu', value: 'Shinryu' },
        { label: 'Unicorn', value: 'Unicorn' },
        { label: 'Valefor', value: 'Valefor' },
        { label: 'Yojimbo', value: 'Yojimbo' },
        { label: 'Zeromus', value: 'Zeromus' },
      ],
    },
  },
  race: [
    { label: 'Hyur', value: 'Hyur' },
    { label: 'Elezen', value: 'Elezen' },
    { label: 'Lalafell', value: 'Lalafell' },
    { label: "Mi'qote", value: "Mi'qote" },
    { label: 'Roegadyn', value: 'Roegadyn' },
    { label: 'Au Ra', value: 'Au Ra' },
    { label: 'Hrothgar', value: 'Hrothgar' },
    { label: 'Viera', value: 'Viera' },
  ],
  job: [
    { label: 'Paladin', value: 'Paladin' },
    { label: 'Warrior', value: 'Warrior' },
    { label: 'Dark Knight', value: 'Dark Knight' },
    { label: 'Gunbreaker', value: 'Gunbreaker' },
    { label: 'White Mage', value: 'White Mage' },
    { label: 'Scholar', value: 'Scholar' },
    { label: 'Astrologian', value: 'Astrologian' },
    { label: 'Sage', value: 'Sage' },
    { label: 'Monk', value: 'Monk' },
    { label: 'Dragoon', value: 'Dragoon' },
    { label: 'Ninja', value: 'Ninja' },
    { label: 'Samurai', value: 'Samurai' },
    { label: 'Reaper', value: 'Reaper' },
    { label: 'Viper', value: 'Viper' },
    { label: 'Bard', value: 'Bard' },
    { label: 'Machinist', value: 'Machinist' },
    { label: 'Dancer', value: 'Dancer' },
    { label: 'Black Mage', value: 'Black Mage' },
    { label: 'Summoner', value: 'Summoner' },
    { label: 'Red Mage', value: 'Red Mage' },
    { label: 'Pictomancer', value: 'Pictomancer' },
  ],
};
